### ISSUE TITLE
when I am click theme change button it show me the red screen

### ISSUE THREAD

**Issue by sukanto3073** [AbdQader/flutter_grocery_app#1]
![366238978_3422336611365039_5235282209614440528_n](https://github.com/AbdQader/flutter_grocery_app/assets/96297630/7d4891b7-57fb-455a-8e64-a6677503ff3c)

**Comment by sukanto3073** [comment]
![366238978_3422336611365039_5235282209614440528_n](https://github.com/AbdQader/flutter_grocery_app/assets/96297630/d6b60bfb-ee66-485b-9c5f-d6d120e62abe)

**Comment by aqsharef** [comment]
Hi,
I tested the app on different devices during debugging and release and haven't had any issues, please provide more details so I can help you

**Comment by sukanto3073** [comment]
hello,
here I am attaching the video for more details also find out some error line 

The following assertion was thrown building ValueListenableBuilder<bool>(dirty, state: _ValueListenableBuilderState<bool>#e339c):
'package:flutter/src/material/theme_data.dart': Failed assertion: line 459 pos 12: 'colorScheme?.brightness == null || brightness == null || colorScheme!.brightness == brightness': is not true.

https://github.com/AbdQader/flutter_grocery_app/assets/96297630/fdb20581-a0df-44d9-af9b-799a6b515923

**Comment by aqsharef** [comment]
This is during debugging right? if so can you tell me what flutter version you have?
also can you try the release version of the app? you can find it in the release section

**Comment by sukanto3073** [comment]
you are correct sir this happened during debug mode but release mode is working perfectly.

why its an error in debugging mode?

**Comment by aqsharef** [comment]
I built this app using Flutter v3.3.6 and if you have a newer version it might be because of it, anyway I will upgrade the app to a newer version in the next few days.
